alter table tomes add column image_url text;

update tomes as t
set titre = v.titre, image_url = v.image_url
from (
  values
  (1, 'À l''aube d''une grande aventure', 'https://covers.openlibrary.org/b/id/11981574-L.jpg'),
  (2, 'Luffy versus la bande à Baggy !!', null),
  (3, 'Piété filiale', 'https://covers.openlibrary.org/b/id/13009506-L.jpg'),
  (4, 'Un chemin en pente raide', 'https://covers.openlibrary.org/b/id/14026866-L.jpg'),
  (5, 'Pour qui sonne le glas', null),
  (6, 'La grande promesse', null),
  (7, 'Le vieux schnock', null),
  (8, 'Pas de souci', null),
  (9, 'Une jeune fille en pleurs', null),
  (10, 'OK, let''s stand up !', 'https://covers.openlibrary.org/b/id/14843415-L.jpg'),
  (11, 'Le pire brigand de tout East-Blue', 'https://covers.openlibrary.org/b/id/15095841-L.jpg'),
  (12, 'La légende est en marche', null),
  (13, 'Sois forte !', null),
  (14, 'L''Instinct', null),
  (15, 'Droit devant!!', null),
  (16, 'Perpétuation', null),
  (17, 'Les cerisiers de Hiluluk', null),
  (18, 'Ace entre en scène', null),
  (19, 'Rébellion', null),
  (20, 'Bataille décisive à Alubarna', null),
  (21, 'Utopie', 'https://covers.openlibrary.org/b/id/13729140-L.jpg'),
  (22, 'Espoir', null),
  (23, 'L''aventure de Vivi', null),
  (24, 'Les rêves', null),
  (25, 'L''homme qui valait cent millions', null),
  (26, 'L''île de dieu', null),
  (27, 'Prélude', null),
  (28, 'Wiper le Berserker', null),
  (29, 'Oratorio', null),
  (30, 'Capriccio', null),
  (31, 'Je suis là', null),
  (32, 'Love Song', null),
  (33, 'Davy Back Fight', null),
  (34, 'Water Seven, La cité sur l''eau', null),
  (35, 'Capitaine', null),
  (36, 'Justice n°9', null),
  (37, 'Tom', null),
  (38, 'Rocketman !', null),
  (39, 'Compétition', null),
  (40, 'Gear', 'https://covers.openlibrary.org/b/id/12376938-L.jpg'),
  (41, 'Déclaration de guerre', 'https://covers.openlibrary.org/b/id/13007833-L.jpg'),
  (42, 'Les pirates face au CP9', 'https://covers.openlibrary.org/b/id/12376940-L.jpg'),
  (43, 'La légende du héros', 'https://covers.openlibrary.org/b/id/13007852-L.jpg'),
  (44, 'Rentrons', 'https://covers.openlibrary.org/b/id/12376942-L.jpg'),
  (45, 'Je comprends ce que vous ressentez', null),
  (46, 'À l''aventure sur l''île fantôme', null),
  (47, 'Ciel nuageux avec risque de chutes d''os', null),
  (48, 'L''aventure d''Odz', null),
  (49, 'Nightmare Luffy', null),
  (50, 'De retour', null),
  (51, 'Les onze supernovae', 'https://covers.openlibrary.org/b/id/12376943-L.jpg'),
  (52, 'Roger & Rayleigh', 'https://covers.openlibrary.org/b/id/12376944-L.jpg'),
  (53, 'Le Tempérament d''un roi', null),
  (54, 'Plus personne ne m''arrêtera', null),
  (55, 'Un travelo en enfer', null),
  (56, 'Merci pour tout', null),
  (57, 'Guerre au sommet', null),
  (58, 'L''ère de Barbe Blanche', null),
  (59, 'La mort de Portgas D. Ace', null),
  (60, 'Petit frère', null),
  (61, 'À l''aube d''une grande aventure vers le nouveau monde', 'https://covers.openlibrary.org/b/id/12376945-L.jpg'),
  (62, 'Périple sur l''île des hommes poissons', null),
  (63, 'Otohime et Tiger', null),
  (64, '100 000 vs 10', null),
  (65, 'Table Rase', null),
  (66, 'Vers le soleil', null),
  (67, 'Cool fight', null),
  (68, 'Alliance entre pirates', 'https://covers.openlibrary.org/b/id/13009514-L.jpg'),
  (69, 'SAD', null),
  (70, 'Doflamingo sort de l''ombre', null),
  (71, 'Le Colisée de tous les dangers', null),
  (72, 'Les Oubliés de Dressrosa', null),
  (73, 'L''Opération Dressrosa S.O.P.', null),
  (74, 'Je serai toujours à tes côtés', 'https://covers.openlibrary.org/b/id/13007854-L.jpg'),
  (75, 'Ma gratitude', 'https://covers.openlibrary.org/b/id/12375944-L.jpg'),
  (76, 'Poursuis ta route !', 'https://covers.openlibrary.org/b/id/12375946-L.jpg'),
  (77, 'Smile', 'https://covers.openlibrary.org/b/id/13007855-L.jpg'),
  (78, 'L''Icône du mal', 'https://covers.openlibrary.org/b/id/13009483-L.jpg'),
  (79, 'Lucy !!', 'https://covers.openlibrary.org/b/id/13009484-L.jpg'),
  (80, 'Vers une bataille sans précédent', 'https://covers.openlibrary.org/b/id/13009488-L.jpg'),
  (81, 'À la rencontre de Maître Chavipère', 'https://covers.openlibrary.org/b/id/13009492-L.jpg'),
  (82, 'Un monde en pleine agitation', 'https://covers.openlibrary.org/b/id/13009494-L.jpg'),
  (83, 'Charlotte Linlin', null),
  (84, 'Luffy versus Sanji', null),
  (85, 'Menteur', 'https://covers.openlibrary.org/b/id/14404625-L.jpg'),
  (86, 'Opération régicide', null),
  (87, 'Impitoyable', 'https://covers.openlibrary.org/b/id/13009505-L.jpg'),
  (88, 'Lionne', 'https://covers.openlibrary.org/b/id/13009508-L.jpg'),
  (89, 'Bad end musical', 'https://covers.openlibrary.org/b/id/13009509-L.jpg'),
  (90, 'La Terre Sainte de Marie Joie', 'https://covers.openlibrary.org/b/id/13009510-L.jpg'),
  (91, 'Aventure au pays des samouraïs', 'https://covers.openlibrary.org/b/id/13009513-L.jpg'),
  (92, 'La grande courtisane Komurasaki', 'https://covers.openlibrary.org/b/id/10418913-L.jpg'),
  (93, 'La coqueluche du village d''Ebisu', 'https://covers.openlibrary.org/b/id/13007856-L.jpg'),
  (94, 'Le rêve des guerriers', 'https://covers.openlibrary.org/b/id/12376951-L.jpg'),
  (95, 'L''aventure d''Oden', 'https://covers.openlibrary.org/b/id/10516358-L.jpg'),
  (96, 'Bouillir, tel est le propre du Oden', 'https://covers.openlibrary.org/b/id/12376947-L.jpg'),
  (97, 'Ma bible', 'https://covers.openlibrary.org/b/id/12376954-L.jpg'),
  (98, 'Les neuf rônins', 'https://covers.openlibrary.org/b/id/12376955-L.jpg'),
  (99, 'Luffy au Chapeau de Paille', 'https://covers.openlibrary.org/b/id/12376956-L.jpg'),
  (100, 'Le fluide royal', 'https://covers.openlibrary.org/b/id/12996669-L.jpg'),
  (101, 'Place aux têtes d''affiche', 'https://covers.openlibrary.org/b/id/12996676-L.jpg'),
  (102, 'Un moment décisif', 'https://covers.openlibrary.org/b/id/12996678-L.jpg'),
  (103, 'Le Guerrier Libérateur', 'https://covers.openlibrary.org/b/id/13131692-L.jpg'),
  (104, 'Momosuke Kozuki, shogun du pays des Wa', 'https://covers.openlibrary.org/b/id/14562157-L.jpg'),
  (105, 'Le Rêve de Luffy', 'https://covers.openlibrary.org/b/id/14562158-L.jpg'),
  (106, 'Le rêve d''un génie', 'https://covers.openlibrary.org/b/id/14564422-L.jpg'),
  (107, 'Le héros de la légende', 'https://covers.openlibrary.org/b/id/15108316-L.jpg'),
  (108, 'Un monde dans lequel mieux vaut mourir', 'https://covers.openlibrary.org/b/id/15108315-L.jpg'),
  (109, 'Toujours De Ton Côté', 'https://covers.openlibrary.org/b/id/15108313-L.jpg'),
  (110, 'Les remous d''une époque', null),
  (111, 'Aventure à Erbaf', null),
  (112, 'Haley', null)
) as v(numero, titre, image_url)
where t.numero = v.numero;
